version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:10.6-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Type check
          command: yarn type
      - run:
          name: Unit test
          command: yarn test:ci
